### PR TITLE
Add auth token

### PR DESCRIPTION
**Pull request by yneves**
This should give the impression of a decent security around the API, although it's almost the same open gate. We can replace the token by real session management in the near future.

### CODE REVIEW

**Comment by yneves** [comment]
@ntgn81 It's safe to merge this before the corresponding UI PR, but not the other way around.

**Comment by ntgn81** [comment]
Hmm this is great stuff. How would we test the api now, though? I think it might be nice to have an endpoint to generate token, given email/firmname. Do you think that's a good idea?

**Comment by yneves** [comment]
How do you test the API now? I don't see tests in the repository.

Not a very good idea. There's no security if you can generate tokens without password.

For running in a controlled environment though, you can just require `utils/crypto.js` and use `.cipher` method. The token now is just the email encrypted with a password, which is the database connection string. 

```js
var crypto = require('utils/crypto.js');
var token = crypto.cipher('nam@toptal.com');
```

Also, the token is not being validated yet, that would be a second step.

**Comment by ntgn81** [comment]
Oh totally, I test it the poor man's way, hitting things directly, lol.

Yeah, definitely not a good idea, it's just might make it a tad harder to hit the url below for a quick test.

https://www.syncids.com/api/matters/1234

But I guess that can be worked around

**Comment by yneves** [comment]
This won't stop working with this PR. I pushed one more change, to check for existing account.

**Comment by yneves** [comment]
Right now the token is just for populating `loginEmail` and `firmName`, it doesn't block access or anything.

**Comment by ntgn81** [comment]
Good point, I completely missed that, lol. Will merge later today. Thanks man!

**Pull request merged**
