### PR TITLE
copy winning doc cited state when deduplicating

### PR DESCRIPTION
**Pull request by yneves**
If the winning document exists and its cited, mark as cited in the updated matters as well.

### CODE REVIEW

**Comment by ntgn81** [comment]
Hmm, the current logic should already persist the cited state of the document, as it's looking into cited/uncited and replaces the winning document there. Does it only fail for specific case?

**Comment by yneves** [comment]
@ntgn81 No, i can reproduce consistently, without these changes, cited state is not copied when the doc is renamed.

**Comment by ntgn81** [comment]
Hmm maybe lets talk about this, this is a related problem, with renaming matter we discussed in Jan

On Mon, Jan 4, 2016 at 9:56 PM, Nam Nguyen <nam.nguyen@toptal.com> wrote:
Rename document # 1 -> 2 - US

- Popup
  Do you want to replace document 1
  with document 2 everywhere for this client?
- ArtDB
  - Remove #1
  - Add #2 if #2 does not exist, do nothing otherwise
    - if #2 does not exist and if it's US look it up and populate #2

- Matters
  - All matters for that client/firmname
  - Rename 1 to 2 in cited/uncited/deleted

@juliejager

**Comment by yneves** [comment]
@ntgn81 Sure we can talk. Let me try to explain, i understand it looks confusing.

Julie wants to copy the cited state from the winning document after replacing. That means if the losing doc is NOT cited in the current matter and it IS cited in the winning doc's matter, it should make it cited for the current matter.

**Comment by yneves** [comment]
Fixed the conflicts, still need anything here before merge? @ntgn81

**Pull request merged**
